//MOSTRAR ALERTAS
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";

//TYPES DE AUTENTICACION
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';